### PR TITLE
Suggest using GitBook to build this

### PR DESCRIPTION
**Pull request by paulkernfeld**
I know it's not in Rust, but I am really enjoying having an ePub of this book!

### CODE REVIEW

**Comment by Gankro** [comment]
So this is the first of gitbook I've heard. Looking into it, it seems like mdbook and rustbook have some incompatibilities, but generally agree on "basic" stuff -- could you clarify this situation with some kind of warning that we only explicitly support mdbook, and gitbook compatibility is incidental and uncertain?

**Comment by paulkernfeld** [comment]
Hmm, the GitHub title for mdBook is actually, "Create book from markdown files. Like Gitbook but implemented in Rust." That said, I think that's a good disclaimer. I've updated the text.

**Comment by paulkernfeld** [comment]
Er... more relevant is the GitHub title for rustbook, which is, "A simplified version of gitbook, atop rustdoc."

**Comment by Gankro** [comment]
Thanks!

**Pull request merged**
