### PR TITLE
Make CI script executable

### PR DESCRIPTION
**Pull request by nertpinx**
The automatic CI cails because of .bonnyci/run.sh missing the executable permission.

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/rust-unofficial/too-many-lists/75/1490994188.93/bonnyci-run-check : FAILURE in 11s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/rust-unofficial/too-many-lists/75/1490994457.97/bonnyci-run-check : FAILURE in 13s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/rust-unofficial/too-many-lists/75/1490994776.28/bonnyci-run-check : FAILURE in 12s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/rust-unofficial/too-many-lists/75/1490994926.47/bonnyci-run-check : FAILURE in 31s

**Comment by nertpinx** [comment]
OK, I really tried, I made the CI actually install rust, but the rustbook does not compile. Maybe later I'll have more time for this. But since I've never used BonnyCI it might not happen. Especially when I was doing this just to make the other pull request (which is just fixing two typos) pass the CI =)

**Pull request closed without merging**
