### PR TITLE
mdbook: Replace deprecated book.json with book.toml

### PR DESCRIPTION
**Pull request by lzutao**
`mdbook` warns when building:

```command line
2019-01-11 16:56:51 [WARN] (mdbook::book): It appears you are still using book.json for configuration.
2019-01-11 16:56:51 [WARN] (mdbook::book): This format is no longer used, so you should migrate to the
2019-01-11 16:56:51 [WARN] (mdbook::book): book.toml format.
2019-01-11 16:56:51 [WARN] (mdbook::book): Check the user guide for migration information:
2019-01-11 16:56:51 [WARN] (mdbook::book):      https://rust-lang-nursery.github.io/mdBook/format/config.html
2019-01-11 16:56:51 [INFO] (mdbook::book): Book building has started
2019-01-11 16:56:51 [INFO] (mdbook::book): Running the html backend
```

### CODE REVIEW

**Comment by Gankro** [comment]
@steveklabnik help i have no idea what this is

**Comment by steveklabnik** [comment]
mdbook, long ago, used a json config file. it now uses a toml config file

**Comment by steveklabnik** [comment]
This PR changes a *lot* more than just the config file though, so I'm not sure it's acceptable.

**Comment by lzutao** [comment]
@steveklabnik Sorry, I will split this PR to two separate PR for easier reviewing.

**Comment by lzutao** [comment]
@Gankro Rebased.

**Pull request merged**
